services:

  app:
    container_name: doc_analista
    build: .
    networks:
      - docNet
      - rede_vps        # conecta na rede do nginx-proxy-manager
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./vectorstore_data:/app/vectorstore
      - ./rag_files:/app/rag_files
      - /root/hf_models:/app/hf_models
    restart: unless-stopped

  redis:
    container_name: doc_redis
    image: redis:7-alpine
    networks:
      - docNet
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

networks:
  docNet:
    driver: bridge
  rede_vps:
    external: true